name: CLI CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test_and_build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm i
      - name: Build the CLI
        run: pnpm build
      - name: Run unit tests
        run: pnpm test:unit
